name: Run Tests and Check Coverage

on:
  pull_request:
    branches:
      - main
    #paths:
     # - './**'  # Ajusta el path según la ubicación de tus archivos de código

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x]  # Puedes usar una versión de Node.js específica

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npx test --verbose --coverage

      #- name: Upload coverage to Codecov
      #  if: always()
      #  uses: codecov/codecov-action@v3
      #  with:
      #    files: ./coverage/*.json
      #    fail_ci_if_error: true
      #    verbose: true
